name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"
        env:
          GH_TOKEN: '${GH_TOKEN}'
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
