name: 'Chromatic Deployment'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - uses: actions/checkout@v1
      - run: yarn
      - name: Publish to Chromatic
      - uses: chromaui/checkout@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
