name: CI
on:
  pull_request:
    branches: [main, development]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install modules
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"
        env:
          GH_TOKEN: '${GH_TOKEN}'
      - name: Run tests
        run: yarn test
