name: CI
on:
  pull_request:
    branches: [main, development]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          yarn config set '//npm.pkg.github.com/:_authToken' "${GHP_TOKEN}"
          yarn
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
      - name: Run tests
        run: yarn test
