name: CI
on:
  pull_request:
    branches: [main, development]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install modules
        run: |
          yarn
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GHP_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          cat .npmrc
      - name: Run tests
        run: yarn test
