name: CI
on:
  pull_request:
    branches: [main, development, next]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHP_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
      - name: Lint Files
        run: yarn test-lint
  jest:
    name: Jest
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHP_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
      - name: Run Unit Tests
        run: yarn test-jest
  e2e:
    name: End<->End
    runs-on: ubuntu-latest
    needs: [jest]
    steps:
      - name: Add Hostname
        run: sudo echo "127.0.0.1 algodex.local" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHP_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
      - name: Run Algodex
        run: yarn build-start &

      # Saucelabs
      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
      - uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: algodex
      - name: Sauce Connect
        run: yarn global add wait-on && wait-on http://alogdex.local:3000 && saucectl run
  chromatic-deployment:
    name: Storybook
    runs-on: ubuntu-latest
    needs: [e2e]
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHP_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
