name: CI
on:
  pull_request:
    branches: [main, development]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GHP_AUTH_TOKEN }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
          SENTRY_AUTH_TOKEN: b4a3e05d4cc54d4c940db6f4cda5765ae1d650cc14c74203aff4fc52cc4a4af9
      - name: Run tests
        run: yarn test
